# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'win1803'

steps:
- script: yarn
  displayName: 'Install dependencies'

- script: yarn build
  displayName: 'Build'
  
- script: yarn test
  displayName: 'Test'

- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    pathtoPublish: '$(Build.SourcesDirectory)/dist'
    artifactName: 'dist'
